const profilData = {
  "Industriell produktion": [
    { id: "TAOP88", code: "TAOP88", name: "Optimering för ingenjörer", hp: 6.0, level: "G2F", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 1, blocks: [1], altPeriods: ["T8-P1"] },
    { id: "TMPS27", code: "TMPS27", name: "Produktionssystem", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 3, blocks: [3] },
    { id: "TDDE56_1", code: "TDDE56", name: "Grunderna i AI och maskininlärning (Del 1)", hp: 3.0, level: "G2F", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 2, blocks: [2], span: 1, altPeriods: ["T9-P1"] },
    { id: "TDDE56_2", code: "TDDE56", name: "Grunderna i AI och maskininlärning (Del 2)", hp: 3.0, level: "G2F", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 1, blocks: [1], span: 1, altPeriods: ["T9-P2"] },
    { id: "TMKO05", code: "TMKO05", name: "Additiv tillverkning för industriella tillämpningar", hp: 6.0, level: "G2F", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 3, blocks: [3] },
    { id: "TMMI46", code: "TMMI46", name: "Industriell automation", hp: 6.0, level: "G2F", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 1, blocks: [1] },
    { id: "TMPS31", code: "TMPS31", name: "Hållbar produktion", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 1, blocks: [1] },
    { id: "TMQU12", code: "TMQU12", name: "Lean Production", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 2, blocks: [2] },
    { id: "TPPE76", code: "TPPE76", name: "Flödesplanering och -styrning", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 4, blocks: [4] },
    { id: "TMPS22", code: "TMPS22", name: "Monteringsteknik", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 3, blocks: [3] },
    { id: "TDDE10", code: "TDDE10", name: "Objektorienterad programmering i Java", hp: 6.0, level: "G2F", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 1, blocks: [1] },
    { id: "TMQU31", code: "TMQU31", name: "Statistisk kvalitetsstyrning", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 2, blocks: [2] },
    { id: "TMPR05", code: "TMPR05", name: "Avancerade produktionsprocesser och -system", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 3, blocks: [3] },
    { id: "TMQU04", code: "TMQU04", name: "Six Sigma Quality", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 2, blocks: [2] },
    { id: "TMPM08_1", code: "TMPM08", name: "Projektkurs avancerad - Industriell produktion (Del 1)", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 1, blocks: [1], span: 1 },
    { id: "TMPM08_2", code: "TMPM08", name: "Projektkurs avancerad - Industriell produktion (Del 2)", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 4, blocks: [4], span: 1 },
    { id: "TMPR07", code: "TMPR07", name: "Virtuell produktion", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 4, blocks: [4] },
    { id: "TMKO02", code: "TMKO02", name: "Material och tillverkningsteknik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 2, blocks: [2], altPeriods: ["T7-P1"] },
    { id: "TPPE16", code: "TPPE16", name: "Produktionsstrategier", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 2, blocks: [2], altPeriods: ["T7-P1"] },
    { id: "TPPE99", code: "TPPE99", name: "Simulering av produktion och logistik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 3, blocks: [3] },
    { id: "TQXX33_1", code: "TQXX33", name: "Examensarbete (Del 1)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P1", defP: "T10-P1", defB: "-", blocks: ["-"], fixed: true, span: 1 },
    { id: "TQXX33_2", code: "TQXX33", name: "Examensarbete (Del 2)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P2", defP: "T10-P2", defB: "-", blocks: ["-"], fixed: true, span: 1 }
  ],
  "Tillämpad mekanik": [
    { id: "TMHL03", code: "TMHL03", name: "Hållfasthetslära: Lätta konstruktioner", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 4, blocks: [4] },
    { id: "TAOP88", code: "TAOP88", name: "Optimering för ingenjörer", hp: 6.0, level: "G2F", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 1, blocks: [1], altPeriods: ["T8-P1"] },
    { id: "TMME40", code: "TMME40", name: "Strukturdynamik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 3, blocks: [3] },
    { id: "TMME67", code: "TMME67", name: "Muskuloskelettär biomekanik och rörelseapparaten", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 2, blocks: [2] },
    { id: "TMMV01", code: "TMMV01", name: "Aerodynamik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 3, blocks: [3] },
    { id: "TMMV18", code: "TMMV18", name: "Fluidmekanik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 1, blocks: [1] },
    { id: "TMHL41", code: "TMHL41", name: "Kontinuumsmekanik", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 4, blocks: [4] },
    { id: "TMME50", code: "TMME50", name: "Flygmekanik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 2, blocks: [2] },
    { id: "TMME68", code: "TMME68", name: "Rotordynamik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 2, blocks: [2] },
    { id: "TMMS20", code: "TMMS20", name: "Strukturoptimering", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 3, blocks: [3] },
    { id: "TMMV62", code: "TMMV62", name: "Modellering och simulering för värmeöverföring", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 1, blocks: [1] },
    { id: "TMHL62", code: "TMHL62", name: "Finita elementmetoden, fortsättningskurs", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 4, blocks: [4] },
    { id: "TMMV08", code: "TMMV08", name: "Beräkningsmetoder i strömningslära", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 3, blocks: [3] },
    { id: "TMKO01", code: "TMKO01", name: "Avancerade material och miljön", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 2, blocks: [2] },
    { id: "TMKO04_1", code: "TMKO04", name: "Kompositmaterial (Del 1)", hp: 3.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 1, blocks: [1], span: 1 },
    { id: "TMKO04_2", code: "TMKO04", name: "Kompositmaterial (Del 2)", hp: 3.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 4, blocks: [4], span: 1 },
    { id: "TMMS30", code: "TMMS30", name: "Flerkroppsmekanik och robotik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 1, blocks: [1] },
    { id: "TMHL61", code: "TMHL61", name: "Skademekanik och livslängdsanalys", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 2, blocks: [2] },
    { id: "TMME11", code: "TMME11", name: "Markfordonsmekanik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 1, blocks: [1] },
    { id: "TMME19", code: "TMME19", name: "Mekanik, fortsättningskurs", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 1, blocks: [1] },
    { id: "TMMV07", code: "TMMV07", name: "Beräkningsmetoder i strömningslära, fk", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 4, blocks: [4] },
    { id: "TMMV63", code: "TMMV63", name: "Beräkningsmetoder för aerodynamik", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 3, blocks: [3] },
    { id: "TMPM10_1", code: "TMPM10", name: "Projektkurs avancerad - Tillämpad mekanik (Del 1)", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: "-", blocks: ["-"], span: 1 },
    { id: "TMPM10_2", code: "TMPM10", name: "Projektkurs avancerad - Tillämpad mekanik (Del 2)", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: "-", blocks: ["-"], span: 1 },
    { id: "TMHL19", code: "TMHL19", name: "Avancerad material- och beräkningsmekanik", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 1, blocks: [1] },
    { id: "TMMV12", code: "TMMV12", name: "Gasturbinteknik", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 4, blocks: [4] },
    { id: "TMMV59", code: "TMMV59", name: "Tillämpning av beräkningsmetoder i strömningslära", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 2, blocks: [2] },
    { id: "TMMV64", code: "TMMV64", name: "Maskininlärning för maskintekniska tillämpningar", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 1, blocks: [1] },
    { id: "TQXX33_1", code: "TQXX33", name: "Examensarbete (Del 1)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P1", defP: "T10-P1", defB: "-", blocks: ["-"], fixed: true, span: 1 },
    { id: "TQXX33_2", code: "TQXX33", name: "Examensarbete (Del 2)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P2", defP: "T10-P2", defB: "-", blocks: ["-"], fixed: true, span: 1 }
  ],
  "Mekatronik": [
    { id: "TMHP02", code: "TMHP02", name: "Fluidmekanisk systemteknik", hp: 6.0, level: "G2F", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 2, blocks: [2] },
    { id: "TSFS09_1", code: "TSFS09", name: "Modellering och reglering av motorer och drivlinor (Del 1)", hp: 3.0, level: "A1N", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 4, blocks: [4], span: 1 },
    { id: "TSFS09_2", code: "TSFS09", name: "Modellering och reglering av motorer och drivlinor (Del 2)", hp: 3.0, level: "A1N", type: "O", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 3, blocks: [3], span: 1 },
    { id: "TSRT06", code: "TSRT06", name: "Reglerteknik, fk", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 1, blocks: [1] },
    { id: "TMHP51", code: "TMHP51", name: "Hydrauliska servosystem", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 4, blocks: [4] },
    { id: "TMME50", code: "TMME50", name: "Flygmekanik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 2, blocks: [2] },
    { id: "TSFS02", code: "TSFS02", name: "Fordonsdynamik med reglering", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 1, blocks: [1] },
    { id: "TAOP88", code: "TAOP88", name: "Optimering för ingenjörer", hp: 6.0, level: "G2F", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 1, blocks: [1], altPeriods: ["T7-P1"] },
    { id: "TMMS30", code: "TMMS30", name: "Flerkroppsmekanik och robotik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 1, blocks: [1] },
    { id: "TSFS04", code: "TSFS04", name: "Elektriska drivsystem", hp: 6.0, level: "G2F", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 4, blocks: [4] },
    { id: "TSRT07", code: "TSRT07", name: "Industriell reglerteknik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 2, blocks: [2] },
    { id: "TMHP06", code: "TMHP06", name: "Fluidmekanisk systemteknik, avancerad kurs", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 2, blocks: [2] },
    { id: "TMME11", code: "TMME11", name: "Markfordonsmekanik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 1, blocks: [1] },
    { id: "TSFS03", code: "TSFS03", name: "Fordonsframdrivningssystem", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 4, blocks: [4] },
    { id: "TSFS19", code: "TSFS19", name: "Batterisystem", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 2, blocks: [2] },
    { id: "TSFS22", code: "TSFS22", name: "Feldetektion och diagnos av tekniska system", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 1, blocks: [1] },
    { id: "TSRT14", code: "TSRT14", name: "Sensorfusion", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 3, blocks: [3] },
    { id: "TMPM06_1", code: "TMPM06", name: "Projektkurs avancerad - Mekatronik (Del 1)", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 4, blocks: [4], span: 1 },
    { id: "TMPM06_2", code: "TMPM06", name: "Projektkurs avancerad - Mekatronik (Del 2)", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: "-", blocks: ["-"], span: 1 },
    { id: "TSRT28_1", code: "TSRT28", name: "Projektkurs i reglerteknik (Del 1)", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 4, blocks: [4], span: 1 },
    { id: "TSRT28_2", code: "TSRT28", name: "Projektkurs i reglerteknik (Del 2)", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 4, blocks: [4], span: 1 },
    { id: "TDDE18_1", code: "TDDE18", name: "Programmera C++ (Del 1)", hp: 3.0, level: "G2F", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 2, blocks: [2], span: 1, altPeriods: ["T7-P1"] },
    { id: "TDDE18_2", code: "TDDE18", name: "Programmera C++ (Del 2)", hp: 3.0, level: "G2F", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 1, blocks: [1], span: 1, altPeriods: ["T7-P2"] },
    { id: "TDDE56_1", code: "TDDE56", name: "Grunderna i AI och maskininlärning (Del 1)", hp: 3.0, level: "G2F", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 2, blocks: [2], span: 1, altPeriods: ["T7-P1"] },
    { id: "TDDE56_2", code: "TDDE56", name: "Grunderna i AI och maskininlärning (Del 2)", hp: 3.0, level: "G2F", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 1, blocks: [1], span: 1, altPeriods: ["T7-P2"] },
    { id: "TMMS32", code: "TMMS32", name: "Modellering och simulering av mekatroniska system", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 3, blocks: [3] },
    { id: "TSFS12", code: "TSFS12", name: "Autonoma farkoster - planering, reglering och lärande system", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 1, blocks: [1] },
    { id: "TSRT92", code: "TSRT92", name: "Modellering och inlärning för dynamiska system", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 3, blocks: [3] },
    { id: "TMKA11", code: "TMKA11", name: "Modellbaserad utveckling av system-av-system", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 3, blocks: [3] },
    { id: "TSRT08", code: "TSRT08", name: "Optimal styrning", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 3, blocks: [3] },
    { id: "TQXX33_1", code: "TQXX33", name: "Examensarbete (Del 1)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P1", defP: "T10-P1", defB: "-", blocks: ["-"], fixed: true, span: 1 },
    { id: "TQXX33_2", code: "TQXX33", name: "Examensarbete (Del 2)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P2", defP: "T10-P2", defB: "-", blocks: ["-"], fixed: true, span: 1 }
  ],
  "Konstruktionsmaterial": [
    { id: "TMKO02", code: "TMKO02", name: "Material och tillverkningsteknik", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 2, blocks: [2], altPeriods: ["T9-P1"] },
    { id: "TAOP88", code: "TAOP88", name: "Optimering för ingenjörer", hp: 6.0, level: "G2F", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 1, blocks: [1], altPeriods: ["T8-P1"] },
    { id: "TMPS27", code: "TMPS27", name: "Produktionssystem", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 3, blocks: [3] },
    { id: "TMKM90", code: "TMKM90", name: "Konstruktionsmaterial - deformationer och brott", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 2, blocks: [2] },
    { id: "TMHL41", code: "TMHL41", name: "Kontinuumsmekanik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 4, blocks: [4] },
    { id: "TMKO05", code: "TMKO05", name: "Additiv tillverkning för industriella tillämpningar", hp: 6.0, level: "G2F", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 3, blocks: [3] },
    { id: "TMPS31", code: "TMPS31", name: "Hållbar produktion", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 1, blocks: [1] },
    { id: "TMKO01", code: "TMKO01", name: "Avancerade material och miljön", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 2, blocks: [2] },
    { id: "TMKO04_1", code: "TMKO04", name: "Kompositmaterial (Del 1)", hp: 3.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 1, blocks: [1], span: 1 },
    { id: "TMKO04_2", code: "TMKO04", name: "Kompositmaterial (Del 2)", hp: 3.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 4, blocks: [4], span: 1 },
    { id: "TFYM04_1", code: "TFYM04", name: "Tillväxt och karakterisering av nanomaterial (Del 1)", hp: 3.0, level: "A1F", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 1, blocks: [1], span: 1 },
    { id: "TFYM04_2", code: "TFYM04", name: "Tillväxt och karakterisering av nanomaterial (Del 2)", hp: 3.0, level: "A1F", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 1, blocks: [1], span: 1 },
    { id: "TMKT48", code: "TMKT48", name: "Konstruktionsoptimering", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 3, blocks: [3] },
    { id: "TMKO03", code: "TMKO03", name: "Metaller för lättviktsapplikationer", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 3, blocks: [3] },
    { id: "TMKO06", code: "TMKO06", name: "Biopolymerer och biokompositer", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 2, blocks: [2] },
    { id: "TMHL61", code: "TMHL61", name: "Skademekanik och livslängdsanalys", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 2, blocks: [2] },
    { id: "TMPM09_1", code: "TMPM09", name: "Projektkurs avancerad - Konstruktionsmaterial (Del 1)", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: "-", blocks: ["-"], span: 1 },
    { id: "TMPM09_2", code: "TMPM09", name: "Projektkurs avancerad - Konstruktionsmaterial (Del 2)", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: "-", blocks: ["-"], span: 1 },
    { id: "TMHL19", code: "TMHL19", name: "Avancerad material- och beräkningsmekanik", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 1, blocks: [1] },
    { id: "TMQU03", code: "TMQU03", name: "Offensiv kvalitetsutveckling, gk", hp: 6.0, level: "G2F", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 2, blocks: [2] },
    { id: "TMMV62", code: "TMMV62", name: "Modellering och simulering för värmeöverföring", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 1, blocks: [1] },
    { id: "TMPR01", code: "TMPR01", name: "Träteknik - Produktframtagning", hp: 6.0, level: "G2F", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 1, blocks: [1] },
    { id: "TQXX33_1", code: "TQXX33", name: "Examensarbete (Del 1)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P1", defP: "T10-P1", defB: "-", blocks: ["-"], fixed: true, span: 1 },
    { id: "TQXX33_2", code: "TQXX33", name: "Examensarbete (Del 2)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P2", defP: "T10-P2", defB: "-", blocks: ["-"], fixed: true, span: 1 }
  ],
  "Produktionsledning": [
    { id: "TAOP88", code: "TAOP88", name: "Optimering för ingenjörer", hp: 6.0, level: "G2F", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 1, blocks: [1], altPeriods: ["T8-P1"] },
    { id: "TPPE16", code: "TPPE16", name: "Produktionsstrategier", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 2, blocks: [2], altPeriods: ["T9-P1"] },
    { id: "TMPS27", code: "TMPS27", name: "Produktionssystem", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 3, blocks: [3] },
    { id: "TPPE76", code: "TPPE76", name: "Flödesplanering och -styrning", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 4, blocks: [4] },
    { id: "TMPS31", code: "TMPS31", name: "Hållbar produktion", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 1, blocks: [1] },
    { id: "TMQU12", code: "TMQU12", name: "Lean Production", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 2, blocks: [2] },
    { id: "TPPE78", code: "TPPE78", name: "Kvantitativa modeller och analys inom verksamhetsstyrning", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 1, blocks: [1] },
    { id: "TMPS22", code: "TMPS22", name: "Monteringsteknik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 3, blocks: [3] },
    { id: "TMQU31", code: "TMQU31", name: "Statistisk kvalitetsstyrning", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 2, blocks: [2] },
    { id: "TPPE74", code: "TPPE74", name: "Design och utveckling av produktionsverksamhet", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 4, blocks: [4] },
    { id: "TMPR05", code: "TMPR05", name: "Avancerade produktionsprocesser och -system", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 3, blocks: [3] },
    { id: "TPPE73_1", code: "TPPE73", name: "Produktionsledningsprojekt (Del 1)", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 4, blocks: [4], span: 1 },
    { id: "TPPE73_2", code: "TPPE73", name: "Produktionsledningsprojekt (Del 2)", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 4, blocks: [4], span: 1 },
    { id: "TAOP34", code: "TAOP34", name: "Optimering av stora system", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 3, blocks: [3] },
    { id: "TMPR07", code: "TMPR07", name: "Virtuell produktion", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 4, blocks: [4] },
    { id: "TPPE99", code: "TPPE99", name: "Simulering av produktion och logistik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 3, blocks: [3] },
    { id: "TAOP18", code: "TAOP18", name: "Optimering av försörjningskedjor", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 1, blocks: [1] },
    { id: "TQXX33_1", code: "TQXX33", name: "Examensarbete (Del 1)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P1", defP: "T10-P1", defB: "-", blocks: ["-"], fixed: true, span: 1 },
    { id: "TQXX33_2", code: "TQXX33", name: "Examensarbete (Del 2)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P2", defP: "T10-P2", defB: "-", blocks: ["-"], fixed: true, span: 1 }
  ],
  "KTPU": [
    { id: "TAOP88", code: "TAOP88", name: "Optimering för ingenjörer", hp: 6.0, level: "G2F", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 1, blocks: [1], altPeriods: ["T8-P1"] },
    { id: "TMPR04_1", code: "TMPR04", name: "Konstruktionsteknik och produktutveckling - studiokurs (Del 1)", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 4, blocks: [4], span: 1 },
    { id: "TMPR04_2", code: "TMPR04", name: "Konstruktionsteknik och produktutveckling - studiokurs (Del 2)", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 4, blocks: [4], span: 1 },
    { id: "TDDE56_1", code: "TDDE56", name: "Grunderna i AI och maskininlärning (Del 1)", hp: 3.0, level: "G2F", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 2, blocks: [2], span: 1, altPeriods: ["T9-P1"] },
    { id: "TDDE56_2", code: "TDDE56", name: "Grunderna i AI och maskininlärning (Del 2)", hp: 3.0, level: "G2F", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 1, blocks: [1], span: 1, altPeriods: ["T9-P2"] },
    { id: "TMME14", code: "TMME14", name: "Maskinelement, fortsättningskurs", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 3, blocks: [3] },
    { id: "TMMI68_1", code: "TMMI68", name: "Cad och ritteknik, fortsättningskurs (Del 1)", hp: 3.0, level: "G2F", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 2, blocks: [2], span: 1 },
    { id: "TMMI68_2", code: "TMMI68", name: "Cad och ritteknik, fortsättningskurs (Del 2)", hp: 3.0, level: "G2F", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 4, blocks: [4], span: 1 },
    { id: "TMHP03", code: "TMHP03", name: "Tekniska system", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 4, blocks: [4] },
    { id: "TMKM90", code: "TMKM90", name: "Konstruktionsmaterial - deformationer och brott", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 2, blocks: [2] },
    { id: "TMKO05", code: "TMKO05", name: "Additiv tillverkning för industriella tillämpningar", hp: 6.0, level: "G2F", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 3, blocks: [3] },
    { id: "TMKT71", code: "TMKT71", name: "Affektiv produktutveckling", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 2, blocks: [2] },
    { id: "TMME68", code: "TMME68", name: "Rotordynamik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 2, blocks: [2] },
    { id: "TMPS31", code: "TMPS31", name: "Hållbar produktion", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 1, blocks: [1] },
    { id: "TMKT48", code: "TMKT48", name: "Konstruktionsoptimering", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 3, blocks: [3] },
    { id: "TMKT74", code: "TMKT74", name: "Avancerad CAD", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 4, blocks: [4] },
    { id: "TDDE10", code: "TDDE10", name: "Objektorienterad programmering i Java", hp: 6.0, level: "G2F", type: "V", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 1, blocks: [1] },
    { id: "TMKT77", code: "TMKT77", name: "Systemsäkerhet", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 4, blocks: [4] },
    { id: "TKMJ29", code: "TKMJ29", name: "Resurseffektiva produkter", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 1, blocks: [1] },
    { id: "TMKT57", code: "TMKT57", name: "Produktmodellering", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 3, blocks: [3] },
    { id: "TMPM05_1", code: "TMPM05", name: "Projektkurs avancerad - Konstruktionsteknik och produktutveckling (Del 1)", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 1, blocks: [1], span: 1 },
    { id: "TMPM05_2", code: "TMPM05", name: "Projektkurs avancerad - Konstruktionsteknik och produktutveckling (Del 2)", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 4, blocks: [4], span: 1 },
    { id: "TMKT79", code: "TMKT79", name: "Kollaborativ multidisciplinär designoptimering", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 2, blocks: [2] },
    { id: "TMQU47", code: "TMQU47", name: "Kvalitetsutveckling och robust konstruktion", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 4, blocks: [4] },
    { id: "TMKA11", code: "TMKA11", name: "Modellbaserad utveckling av system-av-system", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 3, blocks: [3] },
    { id: "TMKU01", code: "TMKU01", name: "Designautomatisering för kundunika produkter", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 2, blocks: [2] },
    { id: "TQXX33_1", code: "TQXX33", name: "Examensarbete (Del 1)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P1", defP: "T10-P1", defB: "-", blocks: ["-"], fixed: true, span: 1 },
    { id: "TQXX33_2", code: "TQXX33", name: "Examensarbete (Del 2)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P2", defP: "T10-P2", defB: "-", blocks: ["-"], fixed: true, span: 1 }
  ],
  "Logistik och supply chain management": [
    { id: "TAOP88", code: "TAOP88", name: "Optimering för ingenjörer", hp: 6.0, level: "G2F", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 1, blocks: [1], altPeriods: ["T8-P1"] },
    { id: "TETS37", code: "TETS37", name: "Grundläggande logistik", hp: 6.0, level: "G2F", type: "O", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 4, blocks: [4] },
    { id: "TDDE56_1", code: "TDDE56", name: "Grunderna i AI och maskininlärning (Del 1)", hp: 3.0, level: "G2F", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 2, blocks: [2], span: 1, altPeriods: ["T9-P1"] },
    { id: "TDDE56_2", code: "TDDE56", name: "Grunderna i AI och maskininlärning (Del 2)", hp: 3.0, level: "G2F", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 1, blocks: [1], span: 1, altPeriods: ["T9-P2"] },
    { id: "TMPS27", code: "TMPS27", name: "Produktionssystem", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P1", defP: "T7-P1", defB: 3, blocks: [3] },
    { id: "TETS27", code: "TETS27", name: "Supply Chain Logistics", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 2, blocks: [2] },
    { id: "TMPS31", code: "TMPS31", name: "Hållbar produktion", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 1, blocks: [1] },
    { id: "TPPE76", code: "TPPE76", name: "Flödesplanering och -styrning", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T7-P2", defP: "T7-P2", defB: 4, blocks: [4] },
    { id: "TETS57", code: "TETS57", name: "Logistikanalys", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T8-P1", defP: "T8-P1", defB: 2, blocks: [2] },
    { id: "TETS36", code: "TETS36", name: "Hållbara logistiksystem", hp: 6.0, level: "A1N", type: "O", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 4, blocks: [4] },
    { id: "TETS56", code: "TETS56", name: "Logistik och kvalitet inom vården", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 3, blocks: [3] },
    { id: "TKMJ29", code: "TKMJ29", name: "Resurseffektiva produkter", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 1, blocks: [1] },
    { id: "TMPR05", code: "TMPR05", name: "Avancerade produktionsprocesser och -system", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T8-P2", defP: "T8-P2", defB: 3, blocks: [3] },
    { id: "TETS38_1", code: "TETS38", name: "Logistikprojekt (Del 1)", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 4, blocks: [4], span: 1 },
    { id: "TETS38_2", code: "TETS38", name: "Logistikprojekt (Del 2)", hp: 6.0, level: "A1F", type: "O", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 2, blocks: [2], span: 1 },
    { id: "TETS58", code: "TETS58", name: "Strategiskt inköp", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 2, blocks: [2] },
    { id: "TPPE99", code: "TPPE99", name: "Simulering av produktion och logistik", hp: 6.0, level: "A1N", type: "V", inriktning: true, period: "T9-P1", defP: "T9-P1", defB: 3, blocks: [3] },
    { id: "TAOP18", code: "TAOP18", name: "Optimering av försörjningskedjor", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 1, blocks: [1] },
    { id: "TETS31", code: "TETS31", name: "Logistikstrategier", hp: 6.0, level: "A1F", type: "V", inriktning: true, period: "T9-P2", defP: "T9-P2", defB: 4, blocks: [4] },
    { id: "TQXX33_1", code: "TQXX33", name: "Examensarbete (Del 1)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P1", defP: "T10-P1", defB: "-", blocks: ["-"], fixed: true, span: 1 },
    { id: "TQXX33_2", code: "TQXX33", name: "Examensarbete (Del 2)", hp: 15, level: "A2E", type: "O", inriktning: true, period: "T10-P2", defP: "T10-P2", defB: "-", blocks: ["-"], fixed: true, span: 1 }
  ],
};

const allCourses = [
  { id: "TANA21", code: "TANA21", name: "Beräkningsmatematik", hp: 6.0, level: "G1F", type: "F", inriktning: false, period: "T7-P1", defB: 3, blocks: [3] },
  { id: "TDDE18_1", code: "TDDE18", name: "Programmera C++ (Del 1)", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 2, blocks: [2], span: 1, multi: true },
  { id: "TDDE18_2", code: "TDDE18", name: "Programmera C++ (Del 2)", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T7-P2", defB: 1, blocks: [1], span: 1, multi: true },
  { id: "TDDE56_1", code: "TDDE56", name: "Grunderna i AI och maskininlärning (Del 1)", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 2, blocks: [2], span: 1, multi: true },
  { id: "TDDE56_2", code: "TDDE56", name: "Grunderna i AI och maskininlärning (Del 2)", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T7-P2", defB: 1, blocks: [1], span: 1, multi: true },
  { id: "TEIM11", code: "TEIM11", name: "Industriell marknadsföring", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 3, blocks: [3] },
  { id: "TEIO19", code: "TEIO19", name: "Industriell organisation", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 4, blocks: [4] },
  { id: "TETS37", code: "TETS37", name: "Grundläggande logistik", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 4, blocks: [4] },
  { id: "TINT01", code: "TINT01", name: "Introduktionskurs i interkulturell kompetens", hp: 2.0, level: "G1N", type: "F", inriktning: false, period: "T7-P1", defB: 1, blocks: [1] },
  { id: "TKMJ31", code: "TKMJ31", name: "Biofuels for Transportation", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 1, blocks: [1] },
  { id: "TMAL02", code: "TMAL02", name: "Flyglära", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 4, blocks: [4] },
  { id: "TMHL03", code: "TMHL03", name: "Hållfasthetslära: Lätta konstruktioner", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 4, blocks: [4] },
  { id: "TMHP02", code: "TMHP02", name: "Fluidmekanisk systemteknik", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 2, blocks: [2] },
  { id: "TMKO02", code: "TMKO02", name: "Material och tillverkningsteknik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 2, blocks: [2] },
  { id: "TMKT80", code: "TMKT80", name: "Träteknik - Material", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 2, blocks: [2] },
  { id: "TMME14", code: "TMME14", name: "Maskinelement, fortsättningskurs", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 3, blocks: [3] },
  { id: "TMME40", code: "TMME40", name: "Strukturdynamik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 3, blocks: [3] },
  { id: "TMME67", code: "TMME67", name: "Muskuloskelettär biomekanik och rörelseapparaten", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 2, blocks: [2] },
  { id: "TMMI68_1", code: "TMMI68", name: "Cad och ritteknik, fortsättningskurs (Del 1)", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 2, blocks: [2], span: 1, multi: true },
  { id: "TMMI68_2", code: "TMMI68", name: "Cad och ritteknik, fortsättningskurs (Del 2)", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T7-P2", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TMMV01", code: "TMMV01", name: "Aerodynamik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 3, blocks: [3] },
  { id: "TMMV18", code: "TMMV18", name: "Fluidmekanik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 1, blocks: [1] },
  { id: "TMPR04_1", code: "TMPR04", name: "Konstruktionsteknik och produktutveckling - studiokurs (Del 1)", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TMPR04_2", code: "TMPR04", name: "Konstruktionsteknik och produktutveckling - studiokurs (Del 2)", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TMPS27", code: "TMPS27", name: "Produktionssystem", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 3, blocks: [3] },
  { id: "TMQU03", code: "TMQU03", name: "Offensiv kvalitetsutveckling, gk", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 2, blocks: [2] },
  { id: "TPPE16", code: "TPPE16", name: "Produktionsstrategier", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 2, blocks: [2] },
  { id: "TSFS09_1", code: "TSFS09", name: "Modellering och reglering av motorer och drivlinor (Del 1)", hp: 3.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TSFS09_2", code: "TSFS09", name: "Modellering och reglering av motorer och drivlinor (Del 2)", hp: 3.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 3, blocks: [3], span: 1, multi: true },
  { id: "TSRT06", code: "TSRT06", name: "Reglerteknik, fk", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 1, blocks: [1] },
  { id: "TMPP02_1", code: "TMPP02", name: "Tävlingsfordonsprojekt (Del 1)", hp: 3.0, level: "G1F", type: "F", inriktning: false, period: "T7-P1", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TMPP02_2", code: "TMPP02", name: "Tävlingsfordonsprojekt (Del 2)", hp: 3.0, level: "G1F", type: "F", inriktning: false, period: "T7-P2", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TATA71", code: "TATA71", name: "Ordinära differentialekvationer och dynamiska system", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P2", defB: 2, blocks: [2] },
  { id: "TEIE42", code: "TEIE42", name: "Industriell försäljning", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 4, blocks: [4] },
  { id: "TETS27", code: "TETS27", name: "Supply Chain Logistics", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 2, blocks: [2] },
  { id: "TGTU49", code: "TGTU49", name: "Teknikhistoria", hp: 6.0, level: "G1F", type: "F", inriktning: false, period: "T7-P2", defB: 1, blocks: [1] },
  { id: "TMES17", code: "TMES17", name: "Building Energy Systems", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 3, blocks: [3] },
  { id: "TMES51", code: "TMES51", name: "Internationella energimarknader", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 2, blocks: [2] },
  { id: "TMHL41", code: "TMHL41", name: "Kontinuumsmekanik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 4, blocks: [4] },
  { id: "TMHP03", code: "TMHP03", name: "Tekniska system", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 4, blocks: [4] },
  { id: "TMHP51", code: "TMHP51", name: "Hydrauliska servosystem", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 4, blocks: [4] },
  { id: "TMKA03", code: "TMKA03", name: "Industridesign", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P2", defB: 1, blocks: [1] },
  { id: "TMKM90", code: "TMKM90", name: "Konstruktionsmaterial - deformationer och brott", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 2, blocks: [2] },
  { id: "TMKO05", code: "TMKO05", name: "Additiv tillverkning för industriella tillämpningar", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P2", defB: 3, blocks: [3] },
  { id: "TMKT71", code: "TMKT71", name: "Affektiv produktutveckling", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 2, blocks: [2] },
  { id: "TMME50", code: "TMME50", name: "Flygmekanik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 2, blocks: [2] },
  { id: "TMME68", code: "TMME68", name: "Rotordynamik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 2, blocks: [2] },
  { id: "TMMI46", code: "TMMI46", name: "Industriell automation", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P2", defB: 1, blocks: [1] },
  { id: "TMMV62", code: "TMMV62", name: "Modellering och simulering för värmeöverföring", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 1, blocks: [1] },
  { id: "TMPR01", code: "TMPR01", name: "Träteknik - Produktframtagning", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P2", defB: 1, blocks: [1] },
  { id: "TMPS31", code: "TMPS31", name: "Hållbar produktion", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 1, blocks: [1] },
  { id: "TMQU12", code: "TMQU12", name: "Lean Production", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 2, blocks: [2] },
  { id: "TPPE76", code: "TPPE76", name: "Flödesplanering och -styrning", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 4, blocks: [4] },
  { id: "TSFS02", code: "TSFS02", name: "Fordonsdynamik med reglering", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 1, blocks: [1] },
  { id: "TSIU02", code: "TSIU02", name: "Datorteknik", hp: 4.0, level: "G1N", type: "F", inriktning: false, period: "T7-P2", defB: 2, blocks: [2] },
  { id: "TAOP88", code: "TAOP88", name: "Optimering för ingenjörer", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 1, blocks: [1], altPeriods: ["T8-P1"] },
  { id: "TAOP88@T8P1", code: "TAOP88", name: "Optimering för ingenjörer (T8)", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T8-P1", defB: 1, blocks: [1], altPeriods: ["T7-P1"] },
  { id: "TKMJ53", code: "TKMJ53", name: "Perspektiv på energi- och miljösystem", hp: 12.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 2, blocks: [2, 4] },
  { id: "TMMS20", code: "TMMS20", name: "Strukturoptimering", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P2", defB: 3, blocks: [3] },
  { id: "TDDE10", code: "TDDE10", name: "Objektorienterad programmering i Java", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T8-P1", defB: 1, blocks: [1] },
  { id: "TDDE50_1", code: "TDDE50", name: "Megagame - design för hållbar utveckling i ett förändrat klimat (Del 1)", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T8-P1", defB: 3, blocks: [3], span: 1, multi: true },
  { id: "TDDE50_2", code: "TDDE50", name: "Megagame - design för hållbar utveckling i ett förändrat klimat (Del 2)", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T8-P2", defB: 3, blocks: [3], span: 1, multi: true },
  { id: "TEIO13", code: "TEIO13", name: "Ledarskap och industriellt förändringsarbete", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 4, blocks: [4] },
  { id: "TETS57", code: "TETS57", name: "Logistikanalys", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T8-P1", defB: 2, blocks: [2] },
  { id: "TFYB11", code: "TFYB11", name: "Materialvetenskap", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 2, blocks: [2] },
  { id: "TGTU91", code: "TGTU91", name: "Retorik i teori och praktik", hp: 6.0, level: "G1F", type: "F", inriktning: false, period: "T8-P1", defB: 2, blocks: [2] },
  { id: "TGTU94", code: "TGTU94", name: "Teknik och etik", hp: 6.0, level: "G1F", type: "F", inriktning: false, period: "T8-P1", defB: 1, blocks: [1] },
  { id: "TINT02_1", code: "TINT02", name: "Interkulturell kompetens och interkulturell kommunikation, fortsättningskurs (Del 1)", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T8-P1", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TINT02_2", code: "TINT02", name: "Interkulturell kompetens och interkulturell kommunikation, fortsättningskurs (Del 2)", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T8-P2", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TKMJ15", code: "TKMJ15", name: "Miljömanagement", hp: 6.0, level: "G1F", type: "F", inriktning: false, period: "T8-P1", defB: 3, blocks: [3] },
  { id: "TKMJ55", code: "TKMJ55", name: "Industriell ekologi", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 1, blocks: [1] },
  { id: "TMAL51", code: "TMAL51", name: "Flygplansprojektering", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T8-P1", defB: 2, blocks: [2] },
  { id: "TMAL56", code: "TMAL56", name: "Flygplanssystem", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T8-P1", defB: 1, blocks: [1] },
  { id: "TMES21", code: "TMES21", name: "Industrial Energy Systems", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T8-P1", defB: 3, blocks: [3] },
  { id: "TMES41", code: "TMES41", name: "Strategisk utveckling av hållbara energisystem", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T8-P1", defB: 1, blocks: [1] },
  { id: "TMES53", code: "TMES53", name: "Energimanagement", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 2, blocks: [2] },
  { id: "TMHL62", code: "TMHL62", name: "Finita elementmetoden, fortsättningskurs", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 4, blocks: [4] },
  { id: "TMKA13", code: "TMKA13", name: "Träteknik - Innovation", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 1, blocks: [1] },
  { id: "TMKO01", code: "TMKO01", name: "Avancerade material och miljön", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 2, blocks: [2] },
  { id: "TMKO04_1", code: "TMKO04", name: "Kompositmaterial (Del 1)", hp: 3.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 1, blocks: [1], span: 1, multi: true },
  { id: "TMKO04_2", code: "TMKO04", name: "Kompositmaterial (Del 2)", hp: 3.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TMKT48", code: "TMKT48", name: "Konstruktionsoptimering", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 3, blocks: [3] },
  { id: "TMKT74", code: "TMKT74", name: "Avancerad CAD", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 4, blocks: [4] },
  { id: "TMMS30", code: "TMMS30", name: "Flerkroppsmekanik och robotik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 1, blocks: [1] },
  { id: "TMMV08", code: "TMMV08", name: "Beräkningsmetoder i strömningslära", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 3, blocks: [3] },
  { id: "TMPS22", code: "TMPS22", name: "Monteringsteknik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 3, blocks: [3] },
  { id: "TMQU31", code: "TMQU31", name: "Statistisk kvalitetsstyrning", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 2, blocks: [2] },
  { id: "TPPE78", code: "TPPE78", name: "Kvantitativa modeller och analys inom verksamhetsstyrning", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 1, blocks: [1] },
  { id: "TSFS04", code: "TSFS04", name: "Elektriska drivsystem", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T8-P1", defB: 4, blocks: [4] },
  { id: "TSIU51_1", code: "TSIU51", name: "Mikrodatorprojekt (Del 1)", hp: 4.0, level: "G1F", type: "F", inriktning: false, period: "T8-P1", defB: 3, blocks: [3], span: 1, multi: true },
  { id: "TSIU51_2", code: "TSIU51", name: "Mikrodatorprojekt (Del 2)", hp: 4.0, level: "G1F", type: "F", inriktning: false, period: "T8-P2", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TSRT07", code: "TSRT07", name: "Industriell reglerteknik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P1", defB: 2, blocks: [2] },
  { id: "TANA31", code: "TANA31", name: "Beräkningsmetoder för ordinära och partiella differentialekvationer", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 2, blocks: [2] },
  { id: "TDDD12", code: "TDDD12", name: "Databasteknik", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T8-P2", defB: 4, blocks: [4] },
  { id: "TEAE13", code: "TEAE13", name: "Affärsrätt", hp: 6.0, level: "G1F", type: "F", inriktning: false, period: "T8-P2", defB: 2, blocks: [2] },
  { id: "TEIO41", code: "TEIO41", name: "Corporate Social Responsibility", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 3, blocks: [3] },
  { id: "TEIO94", code: "TEIO94", name: "Entreprenörskap och idéutveckling", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T8-P2", defB: 2, blocks: [2] },
  { id: "TETS36", code: "TETS36", name: "Hållbara logistiksystem", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 4, blocks: [4] },
  { id: "TETS56", code: "TETS56", name: "Logistik och kvalitet inom vården", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 3, blocks: [3] },
  { id: "TGTU84", code: "TGTU84", name: "Mångfald och genus inom teknikutveckling", hp: 6.0, level: "G1F", type: "F", inriktning: false, period: "T8-P2", defB: 4, blocks: [4] },
  { id: "TGTU95", code: "TGTU95", name: "Vetenskapens och teknologins filosofi", hp: 6.0, level: "G1F", type: "F", inriktning: false, period: "T8-P2", defB: 4, blocks: [4] },
  { id: "TKMJ29", code: "TKMJ29", name: "Resurseffektiva produkter", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 1, blocks: [1] },
  { id: "TMAL06", code: "TMAL06", name: "Aircraft Conceptual Design - Project Course", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T8-P2", defB: 2, blocks: [2] },
  { id: "TMES43", code: "TMES43", name: "Analys och modellering av industriella energisystem", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T8-P2", defB: 3, blocks: [3] },
  { id: "TMHL61", code: "TMHL61", name: "Skademekanik och livslängdsanalys", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 2, blocks: [2] },
  { id: "TMHP06", code: "TMHP06", name: "Fluidmekanisk systemteknik, avancerad kurs", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 2, blocks: [2] },
  { id: "TMKO03", code: "TMKO03", name: "Metaller för lättviktsapplikationer", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 3, blocks: [3] },
  { id: "TMKO06", code: "TMKO06", name: "Biopolymerer och biokompositer", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 2, blocks: [2] },
  { id: "TMKT57", code: "TMKT57", name: "Produktmodellering", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 3, blocks: [3] },
  { id: "TMKT77", code: "TMKT77", name: "Systemsäkerhet", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 4, blocks: [4] },
  { id: "TMKT83", code: "TMKT83", name: "Småskalig förnybar energiomvandling", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 1, blocks: [1] },
  { id: "TMME11", code: "TMME11", name: "Markfordonsmekanik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 1, blocks: [1] },
  { id: "TMME19", code: "TMME19", name: "Mekanik, fortsättningskurs", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 1, blocks: [1] },
  { id: "TMMV07", code: "TMMV07", name: "Beräkningsmetoder i strömningslära, fk", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T8-P2", defB: 4, blocks: [4] },
  { id: "TMMV63", code: "TMMV63", name: "Beräkningsmetoder för aerodynamik", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T8-P2", defB: 3, blocks: [3] },
  { id: "TMPR05", code: "TMPR05", name: "Avancerade produktionsprocesser och -system", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 3, blocks: [3] },
  { id: "TMQU04", code: "TMQU04", name: "Six Sigma Quality", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T8-P2", defB: 2, blocks: [2] },
  { id: "TMQU13", code: "TMQU13", name: "Kundfokuserad produkt- och tjänsteutveckling", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 4, blocks: [4] },
  { id: "TPPE74", code: "TPPE74", name: "Design och utveckling av produktionsverksamhet", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T8-P2", defB: 4, blocks: [4] },
  { id: "TRTE21", code: "TRTE21", name: "Ingenjörens miljöpåverkan med fokus på rening och återvinning", hp: 6.0, level: "G1N", type: "F", inriktning: false, period: "T8-P2", defB: 2, blocks: [2] },
  { id: "TSFS03", code: "TSFS03", name: "Fordonsframdrivningssystem", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 4, blocks: [4] },
  { id: "TSFS17", code: "TSFS17", name: "Elkraftsystem", hp: 6.0, level: "G1F", type: "F", inriktning: false, period: "T8-P2", defB: 2, blocks: [2] },
  { id: "TSFS19", code: "TSFS19", name: "Batterisystem", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 2, blocks: [2] },
  { id: "TSFS22", code: "TSFS22", name: "Feldetektion och diagnos av tekniska system", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 1, blocks: [1] },
  { id: "TFYM04_1", code: "TFYM04", name: "Tillväxt och karakterisering av nanomaterial (Del 1)", hp: 3.0, level: "A1F", type: "F", inriktning: false, period: "T8-P1", defB: 1, blocks: [1], span: 1, multi: true },
  { id: "TFYM04_2", code: "TFYM04", name: "Tillväxt och karakterisering av nanomaterial (Del 2)", hp: 3.0, level: "A1F", type: "F", inriktning: false, period: "T8-P2", defB: 1, blocks: [1], span: 1, multi: true },
  { id: "TSRT14", code: "TSRT14", name: "Sensorfusion", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T8-P2", defB: 3, blocks: [3] },
  { id: "TAOP34", code: "TAOP34", name: "Optimering av stora system", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P1", defB: 3, blocks: [3] },
  // Alternativa tillfällen för kurser som ges i olika terminer beroende på inriktning
  { id: "TDDE56_1@T9P1", code: "TDDE56", name: "Grunderna i AI och maskininlärning (Del 1) [T9]", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T9-P1", defB: 2, blocks: [2], span: 1, altPeriods: ["T7-P1"] },
  { id: "TDDE56_2@T9P2", code: "TDDE56", name: "Grunderna i AI och maskininlärning (Del 2) [T9]", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T9-P2", defB: 1, blocks: [1], span: 1, altPeriods: ["T7-P2"] },
  { id: "TDDE18_1@T7P1", code: "TDDE18", name: "Programmera C++ (Del 1) [T7]", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T7-P1", defB: 2, blocks: [2], span: 1, altPeriods: ["T9-P1"] },
  { id: "TDDE18_2@T7P2", code: "TDDE18", name: "Programmera C++ (Del 2) [T7]", hp: 3.0, level: "G2F", type: "F", inriktning: false, period: "T7-P2", defB: 1, blocks: [1], span: 1, altPeriods: ["T9-P2"] },
  { id: "TPPE16@T9P1", code: "TPPE16", name: "Produktionsstrategier [T9]", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P1", defB: 2, blocks: [2], altPeriods: ["T7-P1"] },
  { id: "TMKO02@T7P1", code: "TMKO02", name: "Material och tillverkningsteknik [T7]", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T7-P1", defB: 2, blocks: [2], altPeriods: ["T9-P1"] },
  { id: "TBME04", code: "TBME04", name: "Anatomi och fysiologi", hp: 6.0, level: "G2F", type: "F", inriktning: false, period: "T9-P1", defB: 3, blocks: [3] },
  { id: "TETS58", code: "TETS58", name: "Strategiskt inköp", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P1", defB: 2, blocks: [2] },
  { id: "TMES27", code: "TMES27", name: "Modellering av energisystem", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P1", defB: 3, blocks: [3] },
  { id: "TMHL19", code: "TMHL19", name: "Avancerad material- och beräkningsmekanik", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: 1, blocks: [1] },
  { id: "TMKT79", code: "TMKT79", name: "Kollaborativ multidisciplinär designoptimering", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: 2, blocks: [2] },
  { id: "TMMV12", code: "TMMV12", name: "Gasturbinteknik", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: 4, blocks: [4] },
  { id: "TMPR07", code: "TMPR07", name: "Virtuell produktion", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P1", defB: 4, blocks: [4] },
  { id: "TMQU47", code: "TMQU47", name: "Kvalitetsutveckling och robust konstruktion", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P1", defB: 4, blocks: [4] },
  { id: "TPPE99", code: "TPPE99", name: "Simulering av produktion och logistik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P1", defB: 3, blocks: [3] },
  { id: "TSFS12", code: "TSFS12", name: "Autonoma farkoster - planering, reglering och lärande system", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P1", defB: 1, blocks: [1] },
  { id: "TSRT92", code: "TSRT92", name: "Modellering och inlärning för dynamiska system", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P1", defB: 3, blocks: [3] },
  { id: "TSTE28", code: "TSTE28", name: "Effektelektronik", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P1", defB: 3, blocks: [3] },
  { id: "TAOP18", code: "TAOP18", name: "Optimering av försörjningskedjor", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: 1, blocks: [1] },
  { id: "TETS31", code: "TETS31", name: "Logistikstrategier", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: 4, blocks: [4] },
  { id: "TKMJ60", code: "TKMJ60", name: "Produkt-tjänsteutveckling för den cirkulära ekonomin", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P2", defB: 3, blocks: [3] },
  { id: "TMES45", code: "TMES45", name: "Energiplanering och modellering av stadsdelar", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: 4, blocks: [4] },
  { id: "TMKA11", code: "TMKA11", name: "Modellbaserad utveckling av system-av-system", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P2", defB: 3, blocks: [3] },
  { id: "TMMV64", code: "TMMV64", name: "Maskininlärning för maskintekniska tillämpningar", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P2", defB: 1, blocks: [1] },
  { id: "TSRT08", code: "TSRT08", name: "Optimal styrning", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P2", defB: 3, blocks: [3] },
  { id: "TSTE26", code: "TSTE26", name: "Elkraftnät och teknik för förnyelsebar elproduktion", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P2", defB: 4, blocks: [4] },
  { id: "TMPE10_1", code: "TMPE10", name: "Projektkurs avancerad - systemanalys inom energi- och miljösystemområdet (Del 1)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TMPE10_2", code: "TMPE10", name: "Projektkurs avancerad - systemanalys inom energi- och miljösystemområdet (Del 2)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TMAL07", code: "TMAL07", name: "Prototype Realization - Project Course", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: 1, blocks: [1] },
  { id: "TMPM10_1", code: "TMPM10", name: "Projektkurs avancerad - Tillämpad mekanik (Del 1)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TMPM10_2", code: "TMPM10", name: "Projektkurs avancerad - Tillämpad mekanik (Del 2)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TMAL08", code: "TMAL08", name: "Aircraft Systems Engineering - Project Course", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: 1, blocks: [1] },
  { id: "TMPM08_1", code: "TMPM08", name: "Projektkurs avancerad - Industriell produktion (Del 1)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: 1, blocks: [1], span: 1, multi: true },
  { id: "TMPM08_2", code: "TMPM08", name: "Projektkurs avancerad - Industriell produktion (Del 2)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TMPM09_1", code: "TMPM09", name: "Projektkurs avancerad - Konstruktionsmaterial (Del 1)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TMPM09_2", code: "TMPM09", name: "Projektkurs avancerad - Konstruktionsmaterial (Del 2)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TMPM05_1", code: "TMPM05", name: "Projektkurs avancerad - Konstruktionsteknik och produktutveckling (Del 1)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: 1, blocks: [1], span: 1, multi: true },
  { id: "TMPM05_2", code: "TMPM05", name: "Projektkurs avancerad - Konstruktionsteknik och produktutveckling (Del 2)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TMKU01", code: "TMKU01", name: "Designautomatisering för kundunika produkter", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: 2, blocks: [2] },
  { id: "TMQU27_1", code: "TMQU27", name: "Kvalitetsutveckling - projektkurs (Del 1)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: 2, blocks: [2], span: 1, multi: true },
  { id: "TMQU27_2", code: "TMQU27", name: "Kvalitetsutveckling - projektkurs (Del 2)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TETS38_1", code: "TETS38", name: "Logistikprojekt (Del 1)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TETS38_2", code: "TETS38", name: "Logistikprojekt (Del 2)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: 2, blocks: [2], span: 1, multi: true },
  { id: "TMPM06_1", code: "TMPM06", name: "Projektkurs avancerad - Mekatronik (Del 1)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TMPM06_2", code: "TMPM06", name: "Projektkurs avancerad - Mekatronik (Del 2)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TSRT28_1", code: "TSRT28", name: "Projektkurs i reglerteknik (Del 1)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TSRT28_2", code: "TSRT28", name: "Projektkurs i reglerteknik (Del 2)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TMMS32", code: "TMMS32", name: "Modellering och simulering av mekatroniska system", hp: 6.0, level: "A1N", type: "F", inriktning: false, period: "T9-P1", defB: 3, blocks: [3] },
  { id: "TPPE73_1", code: "TPPE73", name: "Produktionsledningsprojekt (Del 1)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TPPE73_2", code: "TPPE73", name: "Produktionsledningsprojekt (Del 2)", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P2", defB: 4, blocks: [4], span: 1, multi: true },
  { id: "TMMV59", code: "TMMV59", name: "Tillämpning av beräkningsmetoder i strömningslära", hp: 6.0, level: "A1F", type: "F", inriktning: false, period: "T9-P1", defB: 2, blocks: [2] },
  { id: "TQXX33_1", code: "TQXX33", name: "Examensarbete (Del 1)", hp: 15.0, level: "A2E", type: "F", inriktning: false, period: "T10-P1", defB: "-", blocks: ["-"], span: 1, multi: true },
  { id: "TQXX33_2", code: "TQXX33", name: "Examensarbete (Del 2)", hp: 15.0, level: "A2E", type: "F", inriktning: false, period: "T10-P2", defB: "-", blocks: ["-"], span: 1, multi: true }
];

window.profilData = profilData;
window.allCourses = allCourses;